version: '3.9'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1450:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa__w0rd2022
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
