version: '3.9'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa$$w0rd2022
      # - MSSQL_PID=Express
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8090:80"
